// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringWeb.Models;

namespace MonitoringWeb.Migrations
{
    [DbContext(typeof(MonitoringWebContext))]
    partial class MonitoringWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("MonitoringWeb.SensorsTemp", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CRC");

                    b.Property<DateTime>("LastGet");

                    b.Property<string>("Mount");

                    b.Property<int>("Number");

                    b.Property<double>("Tempreture");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("MonitoringWeb.SensorsTempData", b =>
                {
                    b.Property<string>("Id");

                    b.Property<DateTime>("LastGet");

                    b.Property<bool>("CRC");

                    b.Property<string>("Mount");

                    b.Property<int>("Number");

                    b.Property<double>("Tempreture");

                    b.HasKey("Id", "LastGet");

                    b.ToTable("SensorsData");
                });
#pragma warning restore 612, 618
        }
    }
}
